version: '3.1'

services:

  owncloud:
    container_name: srv-owncloud
    image: owncloud
    restart: always
    ports:
      - 83:80
    networks:
      - net-owncloud
  mysql:
    container_name: srv-mariadb
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - net-owncloud
  adminer:
    container_name: srv-adminer
    image: adminer:latest
    ports:
      - 8081:8080
    restart: always
    networks:
      - net-owncloud
networks:
  net-owncloud: